### ISSUE TITLE
Legion Artifact Weapon Change Stations

### ISSUE THREAD

**Issue by Orphani** [lownignitus/iLvLr#1]
Hello. I just wanted to report that currently with this addon installed no changing area for legion artifact weapons work. The areas in a class order hall where you change the weapons appearance, ect.

**Comment by lownignitus** [comment]
I am not able to reproduce this. I am able to use the Artifact upgrade stations just fine with out making any changes to my code =/

https://imgur.com/a/Wynjq5f
