### ISSUE TITLE
settings don't save

### ISSUE THREAD

**Issue by Neciss** [lownignitus/iLvLr#3]
Heyhey,

I got an issue with the settings

I would like to turn off the durability and colours. It works fine, but everytime the the UI reloads (zone change, logout/login etc.) the settings are resetted. Can't be intended? :/

Greetings

**Comment by lownignitus** [comment]
Any other info, like version you are using?

**Comment by Atysh** [comment]
I have the same issue, using version "v2.3.405"

**Comment by lownignitus** [comment]
variables saved state is fixed

**Comment by Atysh** [comment]
Thank you!
