### ISSUE TITLE
Inspect ilvl

### ISSUE THREAD

**Issue by Bardogfgc** [lownignitus/iLvLr#4]
![420](https://user-images.githubusercontent.com/57969229/69196554-25934b80-0b2f-11ea-9549-bb0d95247e83.png)
On inspect mode, it's impossible to see the exact ilvl that have the inspected person, and can't config the font to be little and nothing like that.
Playing on 2560x1440 in case that info is useful

**Comment by Hemorrhaging** [comment]
This can be fixed by changing the line "iLvLrReportFrame:SetPoint("BOTTOM", InspectFrame, "RIGHT", -45, 15)" in the function iLvLInspecInit() in the file iLvLr.lua to "iLvLrReportFrame:SetPoint("BOTTOM", InspectFrame, "RIGHT", -50, 10)"

**Comment by lownignitus** [comment]
Inspect ilvl doesnt behave as wanted, not always reporting the true ilvl of person being scanned. More pressing things need worked on, like spec swapping and item swapping not always updating the addon. 

So for now, it has been removed from the addon.
