### ISSUE TITLE
9.1 bug found

### ISSUE THREAD

**Issue by jgwallace3** [lownignitus/iLvLr#7]
11x iLvLr\iLvLr-2.4.3.lua:335: attempt to concatenate local 'value' (a nil value)
[string "@iLvLr\iLvLr-2.4.3.lua"]:335: in function `SplitString'
[string "@iLvLr\iLvLr-2.4.3.lua"]:416: in function `fetchGem'
[string "@iLvLr\iLvLr-2.4.3.lua"]:620: in function `makeMod'
[string "@iLvLr\iLvLr-2.4.3.lua"]:278: in function `iLvLrOnItemUpdate'
[string "@iLvLr\iLvLr-2.4.3.lua"]:238: in function <iLvLr\iLvLr.lua:213>

Locals:
seperator = ":"
value = nil
list = <table> {
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = ":"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'value' (a nil value)"

**Comment by malyonsus** [comment]
I _believe_ this is caused by the item link string for legendaries adding a new section (or updating an old one) in the item data encoding in item links. I submitted a possible light-touch fix in PR #6 that just allows for the now-present alphabetical characters and no other change.

**Comment by lownignitus** [comment]
Just getting back into wow afetr a roughly 2 month break. I only just launched game, and @malyonsus suggested fix seems to be working for now. So Ill do some testing, a TOC update, a credit in update notes and push fix within 24 hrs i think.
